/***************************************************************/
/* This class was generated by ds-to-spi-annotations-processor */
/***************************************************************/

public class MockScript_SPI
       extends MockScript
       implements org.daisy.common.spi.ServiceWithProperties
                , org.daisy.common.spi.CreateOnStart {
	
	private static final org.slf4j.Logger spi_log = org.slf4j.LoggerFactory.getLogger(MockScript_SPI.class);
	
	private final java.util.Map spi_props;
	
	public MockScript_SPI() {
		super();
		spi_log.trace("Creating MockScript");
		spi_props = new java.util.HashMap();
		spi_props.put("script.id", "mock-script");
		spi_props.put("script.description", "Does stuff.");
		spi_props.put("script.url", "http://www.daisy.org/pipeline/modules/mock/script.xpl");
		spi_props.put("script.version", "1.0.0");
		spi_log.trace("Activating MockScript");
		java.util.HashMap props = new java.util.HashMap();
		props.put("script.id", "mock-script");
		props.put("script.description", "Does stuff.");
		props.put("script.url", "http://www.daisy.org/pipeline/modules/mock/script.xpl");
		props.put("script.version", "1.0.0");
		activate(props);
	}
	
	public java.util.Map spi_getProperties() {
		return spi_props;
	}
}
